### ISSUE TITLE
loosing input stream after a short while of running

### ISSUE THREAD

**Issue by fletch247** [carstena/game-to-philips-hue#4]
hi,
this is a nice little tool!
it works but always only for a short time. it stops working with the following error:
![screenshot](https://cloud.githubusercontent.com/assets/15935800/11290572/4c979230-8f38-11e5-96c1-f9f6564769cf.png)

the bandicam records screenshots with refreshrate of 0,5s
the config is set up with 500ms

i also tested variations of bandicam 0,5s and 1000ms in game to hue. always the same error.

windows 7 x64, latest java

what do i do wrong?

thanks!

**Comment by polykoma** [comment]
same here.didnt got it working too, yet.

meanwhile i use HueImmersive.jar.

But i really really like to have specific grabbing areas for each lamp which this tool provides....

**Comment by carstena** [comment]
Can you try the new version on the develop branch?
https://github.com/carstena/game-to-philips-hue/blob/develop/EpicGameLightingforHue.zip

**Comment by fletch247** [comment]
thanks for the new version!
sadly it still stops after a short while.
the programm stops prcessing, you can see this by the processed in ms display doesn't change anymore. and as you can see in the screenshot, my bandicam screenshot folder was filled up with images which normally were deleted by gametohue.
is there some more info i can get you to help?
![unbenannt](https://cloud.githubusercontent.com/assets/15935800/11460178/868ba884-96e8-11e5-851e-cbe257e07e15.png)

**Comment by carstena** [comment]
Could you start the jar file from the command line, like this: java -jar EpicGameLightingforHue.jar

**Comment by fletch247** [comment]
hi, i tried this and at some point i got this:

Image processd in 53ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-38-066.jpg:
BufferedImage@4a2f7d71: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 52ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-38-267.jpg:
BufferedImage@33f8237b: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 54ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-38-466.jpg:
BufferedImage@37ba1dfd: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 56ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-38-676.jpg:
BufferedImage@6ca2b735: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 52ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-38-872.jpg:
BufferedImage@6a15170: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 co
lor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDat
aElements 3 dataOff[0] = 2
index size:
2
Image processd in 50ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-39-082.jpg:
BufferedImage@48ecfb7c: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 52ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-39-282.jpg:
BufferedImage@688af268: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 51ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-39-482.jpg:
BufferedImage@ca94787: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 co
lor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDat
aElements 3 dataOff[0] = 2
index size:
2
Image processd in 50ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-39-682.jpg:
BufferedImage@5931334e: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 53ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-39-893.jpg:
BufferedImage@149d07c5: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 52ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-40-089.jpg:
BufferedImage@3f9404ae: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 53ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-40-291.jpg:
BufferedImage@2226f43d: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 51ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-40-500.jpg:
BufferedImage@27b38dae: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 56ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-40-699.jpg:
BufferedImage@b64766: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 col
or space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha = f
alse isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numData
Elements 3 dataOff[0] = 2
index size:
2
Image processd in 52ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-40-900.jpg:
BufferedImage@5af1cd84: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 52ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-41-109.jpg:
BufferedImage@24ea7316: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 72ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-41-316.jpg:
BufferedImage@143a7743: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 55ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-41-516.jpg:
BufferedImage@5556f04e: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 52ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-41-716.jpg:
BufferedImage@691bd594: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 53ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-41-916.jpg:
BufferedImage@7136fc2f: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 51ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-42-116.jpg:
BufferedImage@3ea3b5ad: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 50ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-42-326.jpg:
BufferedImage@dcc98d3: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 co
lor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDat
aElements 3 dataOff[0] = 2
index size:
2
Image processd in 51ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-42-522.jpg:
BufferedImage@103ac5ea: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 50ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-42-732.jpg:
BufferedImage@5f57366e: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 50ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-42-933.jpg:
BufferedImage@328480c2: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 55ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-43-134.jpg:
BufferedImage@11b4090d: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 53ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-43-332.jpg:
BufferedImage@564d2fe0: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 55ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-43-542.jpg:
BufferedImage@78182f35: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 55ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-43-739.jpg:
BufferedImage@4bad5fe: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 co
lor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDat
aElements 3 dataOff[0] = 2
index size:
2
Image processd in 53ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-43-950.jpg:
BufferedImage@35f65ad1: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
index size:
2
Image processd in 53ms
Type for D:\gameToHue_test/temp/bandicam 2015-12-05 02-34-44-149.jpg:
BufferedImage@4cd68a46: type = 5 ColorModel: #pixelBits = 24 numComponents = 3 c
olor space = java.awt.color.ICC_ColorSpace@3dfb21e9 transparency = 1 has alpha =
 false isAlphaPre = false ByteInterleavedRaster: width = 852 height = 479 #numDa
taElements 3 dataOff[0] = 2
java.io.FileNotFoundException: D:\gameToHue_test\temp\bandicam 2015-12-05 02-34-
44-149.jpg (Zugriff verweigert)
        at java.io.RandomAccessFile.open0(Native Method)
        at java.io.RandomAccessFile.open(Unknown Source)
        at java.io.RandomAccessFile.<init>(Unknown Source)
        at javax.imageio.stream.FileImageOutputStream.<init>(Unknown Source)
        at com.sun.imageio.spi.FileImageOutputStreamSpi.createOutputStreamInstan
ce(Unknown Source)
        at javax.imageio.ImageIO.createImageOutputStream(Unknown Source)
        at javax.imageio.ImageIO.write(Unknown Source)
        at com.philips.lighting.gui.ScreenshotsFrame$1.actionPerformed(Screensho
tsFrame.java:267)
        at javax.swing.Timer.fireActionPerformed(Unknown Source)
        at javax.swing.Timer$DoPostEvent.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at javax.imageio.ImageIO.write(Unknown Source)
        at com.philips.lighting.gui.ScreenshotsFrame$1.actionPerformed(Screensho
tsFrame.java:267)
        at javax.swing.Timer.fireActionPerformed(Unknown Source)
        at javax.swing.Timer$DoPostEvent.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
